# Generated by Django 4.0.5 on 2022-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_produitransmissions_produitcable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitcable',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitcamera',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitelephone',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitroute',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitserveur',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitserveurappel',
            old_name='image',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='produitswitch',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='produitcable',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitcamera',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitelephone',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitroute',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitserveur',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitserveurappel',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='produitswitch',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
