# Generated by Django 4.0.6 on 2022-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_produitcable_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitcable',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitcamera',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitelephone',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitroute',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitserveur',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitserveurappel',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='produitswitch',
            name='image_2',
        ),
    ]
