# Generated by Django 4.0.6 on 2022-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produitcable_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitcable',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitcamera',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitelephone',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitroute',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitserveur',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitserveurappel',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produitswitch',
            old_name='image_1',
            new_name='image',
        ),
    ]
