# Generated by Django 4.0.6 on 2022-07-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_image_1_produitcable_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitcable',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitcamera',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitelephone',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitroute',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitserveur',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitserveurappel',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='produitswitch',
            old_name='image',
            new_name='img',
        ),
    ]
