# Generated by Django 4.0.6 on 2022-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_subnames_produitcable_subname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitcable',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='cable'),
        ),
        migrations.AddField(
            model_name='produitcamera',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='camera'),
        ),
        migrations.AddField(
            model_name='produitelephone',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='phone'),
        ),
        migrations.AddField(
            model_name='produitroute',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='router'),
        ),
        migrations.AddField(
            model_name='produitserveurappel',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='serveurappel'),
        ),
        migrations.AddField(
            model_name='produitswitch',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='switch'),
        ),
        migrations.AlterField(
            model_name='produitcable',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cable'),
        ),
        migrations.AlterField(
            model_name='produitcamera',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='camera'),
        ),
        migrations.AlterField(
            model_name='produitelephone',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='phone'),
        ),
        migrations.AlterField(
            model_name='produitroute',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='router'),
        ),
        migrations.AlterField(
            model_name='produitserveurappel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='serveurappel'),
        ),
        migrations.AlterField(
            model_name='produitswitch',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='switch'),
        ),
    ]
