# Generated by Django 4.0.6 on 2022-10-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_formation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formation',
            new_name='produitformation',
        ),
    ]
