# Generated by Django 4.0.6 on 2022-10-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_formation_produitformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='produitformation',
            new_name='formation',
        ),
    ]
