# Generated by Django 4.0.6 on 2022-10-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_produitformation_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='produitcameraptz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subname', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, null=True, upload_to='camera')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='camera')),
                ('detail', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='produitcamerabullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subname', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, null=True, upload_to='camera')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='camera')),
                ('detail', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
            ],
        ),
    ]
