# Generated by Django 4.0.6 on 2022-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_produitserveur_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitactualite',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitapropos',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitcable',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitcamera',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitcamerabullet',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitcameraptz',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitelephone',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitroute',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitserveurappel',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitservice',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='produitswitch',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
